[package]
name = "nyx-stream"
version = "0.1.0"
edition = "2021"

description = "Nyx secure stream layer: frame parser & flow control"
license = "MIT OR Apache-2.0"

build = "build.rs"

[lints]
workspace = true

[dependencies]
nom = { version = "8", default-features = false, features = ["std"] }
nyx-core = { path = "../nyx-core" }
nyx-fec = { path = "../nyx-fec", optional = true }
nyx-mix = { path = "../nyx-mix" }
tokio = { version = "1.37", features = ["sync", "time", "rt", "macros", "io-util", "net"] }
tokio-util = { version = "0.7" }
serde = { version = "1", features=["derive"] }
serde_bytes = "0.11"
ciborium = "0.2"
bitflags = "2.4"
schemars = { version = "0.8", features=["derive"] }
jsonschema = "0.17"
serde_json = "1.0"
tracing = "0.1"
bytes = "1"
once_cell = "1.19"
toml = "0.8"
nyx-crypto = { path = "../nyx-crypto" }
nyx-telemetry = { path = "../nyx-telemetry", optional = true }
hex = "0.4"
semver = { version = "1.0", features = ["serde"] }
libloading = { version = "0.8", optional = true }
thiserror = "1.0"
fastrand = "2.0"
ed25519-dalek = { version = "2", features = ["std", "rand_core"] }
base64 = "0.21"
anyhow = "1.0"
sha2 = "0.10"
getrandom = "0.2"
rand = "0.8"
serde_cbor = "0.11"
async-trait = "0.1"
num-bigint = "0.4"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", optional = true, default-features = false, features = ["sched", "hostname", "fs"] }
caps = { version = "0.5.5", optional = true }
extrasafe = { version = "0.5", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = ["Win32_Foundation","Win32_System_Threading","Win32_System_JobObjects", "Win32_Security"] }
win32job = "2.0"

[dev-dependencies]
tempfile = "3.8"
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
tokio-test = "0.4"
tracing-subscriber = "0.3"
# Updated to latest version to fix protobuf vulnerability (RUSTSEC-2024-0437)
prometheus = "0.14" # for gathering metrics in telemetry feature tests
rand = "0.8"
proptest = "1.5"
futures = "0.3"
nyx-mix = { path = "../nyx-mix" } # For enhanced cover traffic integration tests
tracing-test = "0.2" # For traced test support


[[bench]]
name = "performance_optimization"
harness = false

[features]
default = []
plugin = []
mpr_experimental = []
dynamic_plugin = ["libloading", "nix", "caps", "extrasafe"]
hpke = ["nyx-crypto/hpke"]
fec = ["dep:nyx-fec"]
telemetry = ["dep:nyx-telemetry"]
# OS-level sandbox support (passes through to nyx-core)
os_sandbox = ["nyx-core/os_sandbox"]
# Added to silence unexpected cfg warnings referenced in source
prometheus = []
dynamic_config = []
