[package]
name = "nyx-sdk"
version = "0.1.0"
edition = "2021"

description = "Nyx SDK for application integration with comprehensive stream API"
license = "MIT OR Apache-2.0"

[dependencies]
# Core dependencies
nyx-core = { path = "../nyx-core" }
nyx-stream = { path = "../nyx-stream" }
nyx-crypto = { path = "../nyx-crypto" }

# Async runtime and networking
tokio = { version = "1.47", features = ["full"] }
tokio-stream = "0.1"

# gRPC client for daemon communication - DISABLED: uses ring/openssl
# tonic = { version = "0.10", features = ["transport"] }
prost = "0.12"
prost-types = "0.12"

# Error handling and utilities
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"

# Crypto and hashing for deterministic key derivation in daemon client
ed25519-dalek = { version = "2", features = ["std"] }
blake3 = "1"
hex = "0.4"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"

# Async traits and utilities
async-trait = "0.1"
futures-util = "0.3"
pin-project-lite = "0.2"

# Reconnection and backoff
backoff = { version = "0.4", features = ["tokio"], optional = true }
humantime-serde = "1.1"

# Stream utilities
bytes = "1.5"
futures = "0.3"

# Time and duration utilities
humantime = "2.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.8", features = ["v4", "serde"] }

# Random number generation for jitter
fastrand = "2.0"

# Optional features
tracing-subscriber = "0.3.19"

[build-dependencies]
# tonic-build = "0.10" # DISABLED: uses ring/openssl

[features]
default = []
# Enable stream reconnection with automatic retry
reconnect = ["backoff"]
# Enable comprehensive error propagation
error-propagation = []
# Enable metrics collection
metrics = ["nyx-core/telemetry"]
 # Legacy gRPC backup compatibility flag (to silence cfg in error.rs)
 grpc-backup = []

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
assert_cmd = "2.0"
predicates = "3.0" 
