[package]
name = "nyx-cli"
version = "0.1.0"
edition = "2021"

description = "Nyx command line interface utilities"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.0", default-features = false, features = ["rt", "rt-multi-thread", "macros", "time", "sync", "fs", "io-util", "net", "signal", "io-std"] }
# tonic = "0.10" # DISABLED: uses ring/openssl
prost = "0.12"
prost-types = "0.12"
tokio-stream = "0.1"
crossterm = "0.28"
comfy-table = "7.1"
console = "0.16"
indicatif = "0.17"
byte-unit = "5.1"
ctrlc = "3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }
fastrand = "2.0"
sha2 = "0.10"
tokio-util = { version = "0.7", features = ["codec", "io"] }
futures = "0.3"
ureq = { version = "2.9", default-features = false, features = ["json"] } # Pure Rust HTTP without TLS
urlencoding = "2.1"
md5 = "0.7"
# reqwest = { version = "0.11", features = ["json"] } # DISABLED: uses ring/openssl
url = "2.5"
regex = "1.10"
sysinfo = "0.30"
tracing = "0.1"
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
toml = "0.8" # for nyx.toml (CLI section) parsing
nyx-sdk = { path = "../nyx-sdk" }

[build-dependencies]
# tonic-build = "0.10" # DISABLED: uses ring/openssl

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
tokio-test = "0.4"
sysinfo = "0.30" 

[features]
# Optional build of legacy gRPC-based CLI (archived). Not enabled by default.
grpc-backup = []